---
dependency:
  name: galaxy
  requirements_file: tests/requirements.yml

driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint

platforms:
  - name: centos7
    box: centos/7
    interfaces:
      - network_name: private_network
        type: static
        auto_config: true
        ip: 192.168.50.200
    groups:
      - centos

#  - name: ubuntu16
#    # box: ubuntu/xenial64
#    box: bento/ubuntu-16.04
#    interfaces:
#      - network_name: private_network
#        type: static
#        auto_config: true
#        ip: 192.168.50.202
#    groups:
#      - ubuntu

#  - name: ubuntu18
#    box: ubuntu/bionic64
#    interfaces:
#      - network_name: private_network
#        type: static
#        auto_config: true
#        ip: 192.168.50.203
#    groups:
#      - ubuntu


provisioner:
  name: ansible
  playbooks:
    converge: playbook.yml
  lint:
    name: ansible-lint


scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    # - dependency
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
