---
dependency:
  name: galaxy
  options:
    role-file: molecule/shared/requirements.yml


driver:
  name: docker


lint:
  name: yamllint
  options:
    config-file: molecule/shared/.yaml_lint.yml


platforms:
  - name: "${ROLE_CI_PREFIX:-d}-centos7"
    image: "centos:centos7"
    privileged: false
    pre_build_image: false
    groups:
      - centos

  - name: "${ROLE_CI_PREFIX:-d}-ubuntu1604"
    image: "ubuntu:16.04"
    privileged: false
    pre_build_image: false
    groups:
      - ubuntu


provisioner:
  name: ansible
  playbooks:
    converge: ../shared/playbook.yml
  config_options:
    defaults:
      log_path: "${CLONE_DIR:-.}/ansible.log"
      stdout_callback: debug
      verbosity: 2
    diff:
      always: true
  inventory:
    group_vars:
      ubuntu:
        ansible_python_interpreter: /usr/bin/python3
  lint:
    name: ansible-lint


scenario:
  name: docker
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy


verifier:
  name: testinfra
  directory: ../shared/tests/
  lint:
    name: flake8
